### ISSUE TITLE
Decouple `-use` with working directory

### ISSUE THREAD

**Issue by chapmanjacobd** [scrubbbbs/cbird#6]
## problem

For some of my media I have multiple folders which I'd like to scan. The problem with `-use` is that it provides the same functionality as `cd`--there is no ability to use the same db without resorting to symbolic links, etc.

## suggested behavior

Most CLI tools use positional arguments to define the working directory. You could change the `-use` flag to only mean the path that the `_index` folder will be in and then use positional argument(s) to define the directories to index, defaulting to the `CWD` when nothing is provided as a positional argument.

For example:

```sh
cbird -update
# index folder: CWD/_index/ 
# scan folder: CWD/

cbird -use ~/.local/cbird/video/ -p.alg video -update /san/folder1/
# index folder: ~/.local/cbird/video/_index/
# scan folder: /san/folder1/
```

~~## workaround~~

~~ln -s ~/.local/cbird/video/_index/ . ~~
~~cbird -p.alg video -update~~

This probably messes with `last-added.txt` though--not sure what that is used for

**Comment by scrubbbbs** [comment]
The database stores relative paths for portability, I guess because it seemed natural since the index was going to be tied to the top-level directory. There are some  benefits to this, like being able to move/rename the top directory without breaking the index.

So with your workaround there can be files with the same name/path sharing the index which can't be indexed separately. I'm not sure if that would  fail to index or silently mask the duplicate path. I'm sure there is logic somewhere that assumes all paths are unique.

To share the index without this breakage you would need to link in the other direction and then follow the links with `-i.links`, or use hard links. 

```shell
mkdir global-index; cd global-index
ln -s /san/folder1 ./
ln -s /home/user/Photos  ./
cbird -i.links 1 -update
```

One feature we are missing are filters for `-update` which would be another workaround.

`cbird -use /  -i.include /mnt/share/Photos -include /home/user/Photos  -update`

This would still be enforcing the relative path rule (too many things depend on it now), so it isn't going to do quite what you want. Maybe that concept needs to be revisited to see what all of the tradeoffs are.
